@extends('layouts.app')

@section('title', 'Generated Forms - Fix-It Auto Services')

@section('content')
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col">
            <div class="d-flex justify-content-between align-items-center">
                <h1 class="h3 mb-0">
                    <i class="fas fa-link me-2"></i>Generated Forms
                </h1>
                <div>
                    <a href="{{ route('customers.index') }}" class="btn btn-secondary">
                        <i class="fas fa-arrow-left me-1"></i> Back to Customers
                    </a>
                    <button type="button" class="btn btn-success" onclick="generateCustomerForm()">
                        <i class="fas fa-plus me-1"></i> Generate New Form
                    </button>
                </div>
            </div>
            <p class="text-muted mb-0">Track all generated customer registration forms and their submissions</p>
        </div>
    </div>

    <!-- Active Forms Section -->
    <div class="row mb-5">
        <div class="col">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0">
                        <i class="fas fa-clock me-2"></i>Active Forms
                        <span class="badge bg-light text-primary ms-2">{{ count($activeForms) }}</span>
                    </h5>
                </div>
                <div class="card-body">
                    @if(count($activeForms) > 0)
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Form Token</th>
                                        <th>Email</th>
                                        <th>Generated</th>
                                        <th>Expires</th>
                                        <th>Submissions</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($activeForms as $form)
                                        @php $used = $form['submission_count'] > 0; @endphp
                                        <tr>
                                            <td class="{{ $used ? 'text-decoration-line-through text-danger' : '' }}">
                                                <code class="small {{ $used ? 'text-danger' : '' }}">{{ substr($form['token'], 0, 8) }}...</code>
                                                <br>
                                                <small class="{{ $used ? 'text-danger' : 'text-muted' }}">Generated by: {{ \App\Models\User::find($form['generated_by'])->name ?? 'Unknown' }}</small>
                                            </td>
                                            <td>
                                                @if($form['email'])
                                                    <span class="small">{{ $form['email'] }}</span>
                                                    <button type="button" class="btn btn-sm btn-link p-0 ms-1" onclick="editFormEmail('{{ $form['token'] }}', '{{ $form['email'] }}')" title="Edit email">
                                                        <i class="fas fa-pen text-muted"></i>
                                                    </button>
                                                @else
                                                    <button type="button" class="btn btn-sm btn-outline-secondary" onclick="editFormEmail('{{ $form['token'] }}', '')">
                                                        <i class="fas fa-plus"></i> <small>Add Email</small>
                                                    </button>
                                                @endif
                                            </td>
                                            <td class="{{ $used ? 'text-decoration-line-through text-danger' : '' }}">
                                                <span class="{{ $used ? 'text-danger' : '' }}">{{ $form['generated_at']->format('M j, Y') }}</span>
                                                <br>
                                                <small class="{{ $used ? 'text-danger' : 'text-muted' }}">{{ $form['generated_at']->format('g:i A') }}</small>
                                            </td>
                                            <td class="{{ $used ? 'text-decoration-line-through text-danger' : '' }}">
                                                <span class="{{ $used ? 'text-danger' : '' }}">{{ $form['expires_at']->format('M j, Y') }}</span>
                                                <br>
                                                <small class="{{ $used ? 'text-danger text-decoration-line-through' : 'text-muted' }}">
                                                    {{ $form['is_expired'] ? 'Expired' : 'Expires in ' . $form['expires_at']->diffForHumans() }}
                                                </small>
                                            </td>
                                            <td>
                                                <span class="badge {{ $used ? 'bg-danger' : 'bg-info' }} fs-6">{{ $form['submission_count'] }}</span>
                                                <br>
                                                <small class="{{ $used ? 'text-danger' : 'text-muted' }}">customer(s)</small>
                                            </td>
                                            <td>
                                                @if($used)
                                                    <span class="badge bg-danger">Used</span>
                                                @elseif($form['is_expired'])
                                                    <span class="badge bg-danger">Expired</span>
                                                @else
                                                    <span class="badge bg-success">Active</span>
                                                @endif
                                            </td>
                                            <td>
                                                <div class="btn-group btn-group-sm">
                                                    <button type="button" class="btn btn-outline-primary" onclick="copyFormUrl('{{ $form['form_url'] }}')" {{ $used ? 'disabled' : '' }}>
                                                        <i class="fas fa-copy"></i> Copy
                                                    </button>
                                                    <button type="button" class="btn btn-outline-info" onclick="showFormDetails('{{ $form['token'] }}')">
                                                        <i class="fas fa-eye"></i> View
                                                    </button>
                                                    <button type="button" class="btn btn-outline-dark" onclick="downloadQR('{{ $form['form_url'] }}', '{{ $form['token'] }}')" {{ $used ? 'disabled' : '' }}>
                                                        <i class="fas fa-qrcode"></i> QR
                                                    </button>
                                                    <a href="{{ $form['form_url'] }}" target="_blank" class="btn btn-outline-success" {{ $used ? 'disabled' : '' }}>
                                                        <i class="fas fa-external-link-alt"></i> Open
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="text-center py-5">
                            <i class="fas fa-link fa-3x text-muted mb-3"></i>
                            <h5>No Active Forms</h5>
                            <p class="text-muted">You haven't generated any customer forms yet.</p>
                            <button type="button" class="btn btn-success" onclick="generateCustomerForm()">
                                <i class="fas fa-plus me-1"></i> Generate Your First Form
                            </button>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Form Submissions Section -->
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header bg-success text-white">
                    <h5 class="mb-0">
                        <i class="fas fa-users me-2"></i>Form Submissions
                        <span class="badge bg-light text-success ms-2">{{ $formCustomers->count() }}</span>
                    </h5>
                </div>
                <div class="card-body">
                    @if($formCustomers->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Customer</th>
                                        <th>Submitted</th>
                                        <th>Contact</th>
                                        <th>Form Token</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($formCustomers as $customer)
                                        <tr>
                                            <td>
                                                <strong>{{ $customer->full_name }}</strong>
                                                <br>
                                                <small class="text-muted">ID: {{ $customer->id }}</small>
                                            </td>
                                            <td>
                                                @php $fsa = $customer->form_submitted_at; @endphp
                                                {{ is_string($fsa) ? $fsa : $fsa->format('M j, Y') }}
                                                <br>
                                                <small class="text-muted">{{ is_string($fsa) ? '' : $fsa->format('g:i A') }}</small>
                                            </td>
                                            <td>
                                                @if($customer->phone)
                                                    <i class="fas fa-phone text-muted me-1"></i>{{ $customer->phone }}
                                                    <br>
                                                @endif
                                                @if($customer->email)
                                                    <i class="fas fa-envelope text-muted me-1"></i>{{ $customer->email }}
                                                @endif
                                            </td>
                                            <td>
                                                <code class="small">{{ substr($customer->form_token, 0, 8) }}...</code>
                                            </td>
                                            <td>
                                                @if($customer->is_active)
                                                    <span class="badge bg-success">Active</span>
                                                @else
                                                    <span class="badge bg-danger">Inactive</span>
                                                @endif
                                            </td>
                                            <td>
                                                <div class="btn-group btn-group-sm">
                                                    <a href="{{ route('customers.show', $customer) }}" class="btn btn-outline-primary">
                                                        <i class="fas fa-eye"></i> View
                                                    </a>
                                                    <a href="{{ route('customers.edit', $customer) }}" class="btn btn-outline-warning">
                                                        <i class="fas fa-edit"></i> Edit
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="text-center py-5">
                            <i class="fas fa-users fa-3x text-muted mb-3"></i>
                            <h5>No Form Submissions Yet</h5>
                            <p class="text-muted">No customers have submitted forms yet.</p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Form Generation Modal (from customers index) -->
<div class="modal fade" id="formGenerationModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-success text-white">
                <h5 class="modal-title">
                    <i class="fas fa-link me-2"></i>Customer Form Generated
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="alert alert-success">
                    <i class="fas fa-check-circle me-2"></i>
                    <strong>Success!</strong> Customer form has been generated successfully.
                </div>
                
                <div class="mb-3">
                    <h6 class="mb-2">Email (for notification):</h6>
                    <div class="input-group">
                        <input type="email" class="form-control" id="generatedFormEmail" placeholder="fixitautoservicescenter@gmail.com" readonly>
                        <button class="btn btn-outline-secondary" type="button" onclick="editFormEmailFromModal()">
                            <i class="fas fa-pen"></i> Change
                        </button>
                    </div>
                    <small class="text-muted">Customer registration notifications will be sent to this email.</small>
                </div>
                
                <div class="mb-4">
                    <h6 class="mb-2">Form URL:</h6>
                    <div class="input-group">
                        <input type="text" class="form-control" id="formUrl" readonly>
                        <button class="btn btn-outline-secondary" type="button" onclick="copyFormUrlFromModal()">
                            <i class="fas fa-copy"></i> Copy
                        </button>
                    </div>
                    <small class="text-muted">This link will expire in 7 days.</small>
                </div>
                
                <div class="mb-4">
                    <h6 class="mb-2">QR Code:</h6>
                    <div class="text-center">
                        <img id="qrCodeImage" src="" alt="QR Code" class="img-fluid" style="max-width: 200px;">
                        <div class="mt-2 d-flex justify-content-center gap-2">
                            <button class="btn btn-sm btn-outline-dark" onclick="downloadQrImage(document.getElementById('qrCodeImage').src, 'customer-form-qr.png')">
                                <i class="fas fa-download me-1"></i> Download QR
                            </button>
                            <button class="btn btn-sm btn-outline-secondary" onclick="copyQrImage(document.getElementById('qrCodeImage').src)">
                                <i class="fas fa-image me-1"></i> Copy Image
                            </button>
                        </div>
                        <p class="text-muted mt-2">Scan this QR code to access the form on mobile devices</p>
                    </div>
                </div>
                
                <div class="alert alert-info">
                    <i class="fas fa-info-circle me-2"></i>
                    <strong>How to use:</strong> Send this link or QR code to customers. They can fill out the form to register themselves, which helps prevent spam submissions.
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="openFormUrlFromModal()">
                    <i class="fas fa-external-link-alt me-2"></i> Open Form
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Loading Modal -->
<div class="modal fade" id="loadingModal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body text-center">
                <div class="spinner-border text-primary" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
                <p class="mt-2 mb-0">Generating form...</p>
            </div>
        </div>
    </div>
</div>

<!-- Form Details Modal -->
<div class="modal fade" id="formDetailsModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-white">
                <h5 class="modal-title">
                    <i class="fas fa-info-circle me-2"></i>Form Details
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="formDetailsContent">
                <!-- Content will be loaded via JavaScript -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Edit Email Modal -->
<div class="modal fade" id="editEmailModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-secondary text-white">
                <h5 class="modal-title">
                    <i class="fas fa-envelope me-2"></i>Edit Form Email
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p class="text-muted">Set the email address that receives notifications when a customer submits this form.</p>
                <div class="mb-3">
                    <label for="editEmailInput" class="form-label">Notification Email</label>
                    <input type="email" class="form-control" id="editEmailInput" placeholder="fixitautoservicescenter@gmail.com">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="saveEmailBtn" onclick="saveFormEmail()">
                    <i class="fas fa-save me-1"></i> Save Email
                </button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    function generateCustomerForm() {
        // Prompt for email first
        const email = prompt('Enter email for notification (optional, press Cancel to skip):', '');
        
        // Show loading modal
        const loadingModalElement = document.getElementById('loadingModal');
        const loadingModal = bootstrap.Modal.getOrCreateInstance(loadingModalElement);
        loadingModal.show();
        
        // Generate form via AJAX
        const bodyData = {};
        if (email && email.trim() !== '') {
            bodyData.email = email.trim();
        }
        
        fetch('{{ route("customers.generate-form") }}', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': '{{ csrf_token() }}',
                'Accept': 'application/json'
            },
            body: JSON.stringify(bodyData)
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(result => {
            // Hide loading modal
            loadingModal.hide();
            
            if (result.success) {
                // Populate modal with form data
                document.getElementById('formUrl').value = result.form_url;
                document.getElementById('qrCodeImage').src = result.qr_code_url;
                document.getElementById('generatedFormEmail').value = result.email || '';
                
                // Show the form generation modal
                const formModalElement = document.getElementById('formGenerationModal');
                const formModal = bootstrap.Modal.getOrCreateInstance(formModalElement);
                formModal.show();
                
                // Refresh page after 2 seconds to show new form in list
                setTimeout(() => {
                    window.location.reload();
                }, 2000);
            } else {
                alert('Error: ' + result.message);
            }
        })
        .catch(error => {
            // Hide loading modal
            loadingModal.hide();
            alert('Network error. Please try again. Error: ' + error.message);
            console.error('Error:', error);
        });
    }
    
    function copyFormUrl(url) {
        navigator.clipboard.writeText(url).then(() => {
            // Show success feedback
            alert('Form URL copied to clipboard!');
        }).catch(err => {
            console.error('Failed to copy: ', err);
            alert('Failed to copy to clipboard');
        });
    }
    
    function copyFormUrlFromModal() {
        const formUrlInput = document.getElementById('formUrl');
        formUrlInput.select();
        formUrlInput.setSelectionRange(0, 99999); // For mobile devices
        
        try {
            navigator.clipboard.writeText(formUrlInput.value);
            
            // Show success feedback
            const copyButton = event.target.closest('button');
            const originalHtml = copyButton.innerHTML;
            copyButton.innerHTML = '<i class="fas fa-check"></i> Copied!';
            copyButton.classList.remove('btn-outline-secondary');
            copyButton.classList.add('btn-success');
            
            setTimeout(() => {
                copyButton.innerHTML = originalHtml;
                copyButton.classList.remove('btn-success');
                copyButton.classList.add('btn-outline-secondary');
            }, 2000);
        } catch (err) {
            console.error('Failed to copy: ', err);
            alert('Failed to copy to clipboard');
        }
    }
    
    function openFormUrlFromModal() {
        const formUrl = document.getElementById('formUrl').value;
        window.open(formUrl, '_blank');
    }
    
    function downloadQR(url, token) {
        const qrUrl = 'https://api.qrserver.com/v1/create-qr-code/?size=500x500&data=' + encodeURIComponent(url);
        // Use canvas to download cross-origin image reliably
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.onload = function() {
            const c = document.createElement('canvas');
            c.width = img.width;
            c.height = img.height;
            const ctx = c.getContext('2d');
            ctx.drawImage(img, 0, 0);
            const link = document.createElement('a');
            link.download = 'customer-form-' + token.substring(0, 8) + '-qr.png';
            link.href = c.toDataURL('image/png');
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        };
        img.onerror = function() {
            // Fallback: direct download attempt
            const link = document.createElement('a');
            link.href = qrUrl;
            link.download = 'customer-form-' + token.substring(0, 8) + '-qr.png';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        };
        img.src = qrUrl;
    }

    function downloadQrImage(qrUrl, filename) {
        // Generic QR download: canvas-based to bypass CORS issues
        if (!qrUrl) return;
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.onload = function() {
            const c = document.createElement('canvas');
            c.width = img.width;
            c.height = img.height;
            const ctx = c.getContext('2d');
            ctx.drawImage(img, 0, 0);
            const link = document.createElement('a');
            link.download = filename || 'qr-code.png';
            link.href = c.toDataURL('image/png');
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        };
        img.onerror = function() {
            const link = document.createElement('a');
            link.href = qrUrl;
            link.download = filename || 'qr-code.png';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        };
        img.src = qrUrl;
    }

    function copyQrImage(qrUrl) {
        // Copy QR image to clipboard using canvas
        if (!qrUrl) return;
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.onload = function() {
            const c = document.createElement('canvas');
            c.width = img.width;
            c.height = img.height;
            const ctx = c.getContext('2d');
            ctx.drawImage(img, 0, 0);
            c.toBlob(function(blob) {
                if (!blob) return;
                navigator.clipboard.write([
                    new ClipboardItem({ 'image/png': blob })
                ]).then(function() {
                    alert('QR code copied to clipboard!');
                }).catch(function() {
                    // Fallback: download
                    const link = document.createElement('a');
                    link.download = 'qr-code.png';
                    link.href = c.toDataURL('image/png');
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                });
            });
        };
        img.onerror = function() {
            alert('Failed to load QR code image for copying. Try downloading instead.');
        };
        img.src = qrUrl;
    }

    let currentEditToken = '';
    let currentEditEmail = '';

    function editFormEmail(token, email) {
        currentEditToken = token;
        currentEditEmail = email;
        document.getElementById('editEmailInput').value = email;
        document.getElementById('saveEmailBtn').disabled = false;
        document.getElementById('saveEmailBtn').innerHTML = '<i class="fas fa-save me-1"></i> Save Email';
        
        const editModal = new bootstrap.Modal(document.getElementById('editEmailModal'));
        editModal.show();
    }

    function editFormEmailFromModal() {
        const token = ''; // Will be set after generation
        const email = document.getElementById('generatedFormEmail').value;
        editFormEmail(token, email);
    }

    function saveFormEmail() {
        const email = document.getElementById('editEmailInput').value.trim();
        if (!email) {
            alert('Please enter an email address.');
            return;
        }
        
        const saveBtn = document.getElementById('saveEmailBtn');
        saveBtn.disabled = true;
        saveBtn.innerHTML = '<span class="spinner-border spinner-border-sm me-1"></span> Saving...';
        
        fetch('{{ url("/api/customer-form") }}/' + currentEditToken + '/email', {
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': '{{ csrf_token() }}',
                'Accept': 'application/json'
            },
            body: JSON.stringify({ email: email })
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Update the modal and the list
                document.getElementById('generatedFormEmail').value = email;
                
                const editModalEl = document.getElementById('editEmailModal');
                const editModal = bootstrap.Modal.getInstance(editModalEl);
                if (editModal) editModal.hide();
                
                // Refresh the page to update the list
                window.location.reload();
            } else {
                alert('Error: ' + data.message);
                saveBtn.disabled = false;
                saveBtn.innerHTML = '<i class="fas fa-save me-1"></i> Save Email';
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Network error. Please try again.');
            saveBtn.disabled = false;
            saveBtn.innerHTML = '<i class="fas fa-save me-1"></i> Save Email';
        });
    }

    function showFormDetails(token) {
        // Fetch form details via AJAX
        fetch(`/api/customer-form/${token}/details`, {
            method: 'GET',
            headers: {
                'Accept': 'application/json',
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Populate modal with form details
                const modalContent = document.getElementById('formDetailsContent');
                modalContent.innerHTML = `
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Form Information</h6>
                            <table class="table table-sm">
                                <tr>
                                    <th>Token:</th>
                                    <td><code>${data.form.token}</code></td>
                                </tr>
                                <tr>
                                    <th>Generated:</th>
                                    <td>${data.form.generated_at}</td>
                                </tr>
                                <tr>
                                    <th>Generated By:</th>
                                    <td>${data.form.generated_by}</td>
                                </tr>
                                <tr>
                                    <th>Expires:</th>
                                    <td>${data.form.expires_at}</td>
                                </tr>
                                <tr>
                                    <th>Status:</th>
                                    <td>
                                        ${data.form.is_expired ? 
                                            '<span class="badge bg-danger">Expired</span>' : 
                                            '<span class="badge bg-success">Active</span>'}
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <h6>Submissions</h6>
                            <div class="text-center py-4">
                                <h1 class="display-1 text-primary">${data.form.submission_count}</h1>
                                <p class="text-muted">Customer(s) Registered</p>
                            </div>
                        </div>
                    </div>
                    
                        <div class="mt-3">
                        <h6>Notification Email</h6>
                        <div class="input-group">
                            <input type="text" class="form-control" id="detailsFormEmail" value="${data.form.email || '(not set)'}" readonly>
                            <button class="btn btn-outline-secondary" type="button" onclick="editFormEmail('${data.form.token}', '${data.form.email || ''}')">
                                <i class="fas fa-pen"></i> Change
                            </button>
                        </div>
                        <small class="text-muted">Customer registration notifications sent to this email.</small>
                    </div>
                    
                    <div class="mt-4">
                        <h6>Form URL</h6>
                        <div class="input-group">
                            <input type="text" class="form-control" value="${data.form.form_url}" readonly>
                            <button class="btn btn-outline-primary" type="button" onclick="copyFormUrl('${data.form.form_url}')">
                                <i class="fas fa-copy"></i> Copy
                            </button>
                        </div>
                    </div>
                    
                    <div class="mt-4">
                        <h6>QR Code <span class="text-muted small">(click to open in new tab)</span></h6>
                        <div class="text-center">
                            <img src="${data.form.qr_code_url}" alt="QR Code" class="img-fluid" style="max-width: 150px;">
                            <div class="mt-2 d-flex justify-content-center gap-2">
                                <button class="btn btn-sm btn-outline-dark" onclick="downloadQrImage('${data.form.qr_code_url}', 'customer-form-${data.form.token.substring(0,8)}-qr.png')">
                                    <i class="fas fa-download me-1"></i> Download
                                </button>
                                <button class="btn btn-sm btn-outline-secondary" onclick="copyQrImage('${data.form.qr_code_url}')">
                                    <i class="fas fa-image me-1"></i> Copy Image
                                </button>
                            </div>
                        </div>
                    </div>
                `;
                
                // Attach modal data for download/copy functions
                const detailsModalEl = document.getElementById('formDetailsModal');
                detailsModalEl.dataset.formUrl = data.form.form_url;
                detailsModalEl.dataset.qrUrl = data.form.qr_code_url;

                // Show the modal
                const detailsModal = new bootstrap.Modal(detailsModalEl);
                detailsModal.show();
            } else {
                alert('Error: ' + data.message);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Failed to load form details');
        });
    }
</script>
@endpush