@extends('layouts.app')

@section('title', 'Generated Forms - Fix-It Auto Services')

@section('content')
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col">
            <div class="d-flex justify-content-between align-items-center">
                <h1 class="h3 mb-0">
                    <i class="fas fa-link me-2"></i>Generated Forms
                </h1>
                <div>
                    <a href="{{ route('customers.index') }}" class="btn btn-secondary">
                        <i class="fas fa-arrow-left me-1"></i> Back to Customers
                    </a>
                    <button type="button" class="btn btn-success" onclick="generateCustomerForm()">
                        <i class="fas fa-plus me-1"></i> Generate New Form
                    </button>
                </div>
            </div>
            <p class="text-muted mb-0">Track all generated customer registration forms and their submissions</p>
        </div>
    </div>

    <!-- Active Forms Section -->
    <div class="row mb-5">
        <div class="col">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0">
                        <i class="fas fa-clock me-2"></i>Active Forms
                        <span class="badge bg-light text-primary ms-2">{{ count($activeForms) }}</span>
                    </h5>
                </div>
                <div class="card-body">
                    @if(count($activeForms) > 0)
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Form Token</th>
                                        <th>Generated</th>
                                        <th>Expires</th>
                                        <th>Submissions</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($activeForms as $form)
                                        @php $used = $form['submission_count'] > 0; @endphp
                                        <tr>
                                            <td class="{{ $used ? 'text-decoration-line-through text-danger' : '' }}">
                                                <code class="small {{ $used ? 'text-danger' : '' }}">{{ substr($form['token'], 0, 8) }}...</code>
                                                <br>
                                                <small class="{{ $used ? 'text-danger' : 'text-muted' }}">Generated by: {{ \App\Models\User::find($form['generated_by'])->name ?? 'Unknown' }}</small>
                                            </td>
                                            <td class="{{ $used ? 'text-decoration-line-through text-danger' : '' }}">
                                                <span class="{{ $used ? 'text-danger' : '' }}">{{ $form['generated_at']->format('M j, Y') }}</span>
                                                <br>
                                                <small class="{{ $used ? 'text-danger' : 'text-muted' }}">{{ $form['generated_at']->format('g:i A') }}</small>
                                            </td>
                                            <td class="{{ $used ? 'text-decoration-line-through text-danger' : '' }}">
                                                <span class="{{ $used ? 'text-danger' : '' }}">{{ $form['expires_at']->format('M j, Y') }}</span>
                                                <br>
                                                <small class="{{ $used ? 'text-danger text-decoration-line-through' : 'text-muted' }}">
                                                    {{ $form['is_expired'] ? 'Expired' : 'Expires in ' . $form['expires_at']->diffForHumans() }}
                                                </small>
                                            </td>
                                            <td>
                                                <span class="badge {{ $used ? 'bg-danger' : 'bg-info' }} fs-6">{{ $form['submission_count'] }}</span>
                                                <br>
                                                <small class="{{ $used ? 'text-danger' : 'text-muted' }}">customer(s)</small>
                                            </td>
                                            <td>
                                                @if($used)
                                                    <span class="badge bg-danger">Used</span>
                                                @elseif($form['is_expired'])
                                                    <span class="badge bg-danger">Expired</span>
                                                @else
                                                    <span class="badge bg-success">Active</span>
                                                @endif
                                            </td>
                                            <td>
                                                <div class="btn-group btn-group-sm">
                                                    <button type="button" class="btn btn-outline-primary" onclick="copyFormUrl('{{ $form['form_url'] }}')" {{ $used ? 'disabled' : '' }}>
                                                        <i class="fas fa-copy"></i> Copy
                                                    </button>
                                                    <button type="button" class="btn btn-outline-info" onclick="showFormDetails('{{ $form['token'] }}')">
                                                        <i class="fas fa-eye"></i> View
                                                    </button>
                                                    <a href="{{ $form['form_url'] }}" target="_blank" class="btn btn-outline-success" {{ $used ? 'disabled' : '' }}>
                                                        <i class="fas fa-external-link-alt"></i> Open
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="text-center py-5">
                            <i class="fas fa-link fa-3x text-muted mb-3"></i>
                            <h5>No Active Forms</h5>
                            <p class="text-muted">You haven't generated any customer forms yet.</p>
                            <button type="button" class="btn btn-success" onclick="generateCustomerForm()">
                                <i class="fas fa-plus me-1"></i> Generate Your First Form
                            </button>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Form Submissions Section -->
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header bg-success text-white">
                    <h5 class="mb-0">
                        <i class="fas fa-users me-2"></i>Form Submissions
                        <span class="badge bg-light text-success ms-2">{{ $formCustomers->count() }}</span>
                    </h5>
                </div>
                <div class="card-body">
                    @if($formCustomers->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Customer</th>
                                        <th>Submitted</th>
                                        <th>Contact</th>
                                        <th>Form Token</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($formCustomers as $customer)
                                        <tr>
                                            <td>
                                                <strong>{{ $customer->full_name }}</strong>
                                                <br>
                                                <small class="text-muted">ID: {{ $customer->id }}</small>
                                            </td>
                                            <td>
                                                {{ $customer->form_submitted_at->format('M j, Y') }}
                                                <br>
                                                <small class="text-muted">{{ $customer->form_submitted_at->format('g:i A') }}</small>
                                            </td>
                                            <td>
                                                @if($customer->phone)
                                                    <i class="fas fa-phone text-muted me-1"></i>{{ $customer->phone }}
                                                    <br>
                                                @endif
                                                @if($customer->email)
                                                    <i class="fas fa-envelope text-muted me-1"></i>{{ $customer->email }}
                                                @endif
                                            </td>
                                            <td>
                                                <code class="small">{{ substr($customer->form_token, 0, 8) }}...</code>
                                            </td>
                                            <td>
                                                @if($customer->is_active)
                                                    <span class="badge bg-success">Active</span>
                                                @else
                                                    <span class="badge bg-danger">Inactive</span>
                                                @endif
                                            </td>
                                            <td>
                                                <div class="btn-group btn-group-sm">
                                                    <a href="{{ route('customers.show', $customer) }}" class="btn btn-outline-primary">
                                                        <i class="fas fa-eye"></i> View
                                                    </a>
                                                    <a href="{{ route('customers.edit', $customer) }}" class="btn btn-outline-warning">
                                                        <i class="fas fa-edit"></i> Edit
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="text-center py-5">
                            <i class="fas fa-users fa-3x text-muted mb-3"></i>
                            <h5>No Form Submissions Yet</h5>
                            <p class="text-muted">No customers have submitted forms yet.</p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Form Generation Modal (from customers index) -->
<div class="modal fade" id="formGenerationModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-success text-white">
                <h5 class="modal-title">
                    <i class="fas fa-link me-2"></i>Customer Form Generated
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="alert alert-success">
                    <i class="fas fa-check-circle me-2"></i>
                    <strong>Success!</strong> Customer form has been generated successfully.
                </div>
                
                <div class="mb-4">
                    <h6 class="mb-2">Form URL:</h6>
                    <div class="input-group">
                        <input type="text" class="form-control" id="formUrl" readonly>
                        <button class="btn btn-outline-secondary" type="button" onclick="copyFormUrlFromModal()">
                            <i class="fas fa-copy"></i> Copy
                        </button>
                    </div>
                    <small class="text-muted">This link will expire in 7 days.</small>
                </div>
                
                <div class="mb-4">
                    <h6 class="mb-2">QR Code:</h6>
                    <div class="text-center">
                        <img id="qrCodeImage" src="" alt="QR Code" class="img-fluid" style="max-width: 200px;">
                        <p class="text-muted mt-2">Scan this QR code to access the form on mobile devices</p>
                    </div>
                </div>
                
                <div class="alert alert-info">
                    <i class="fas fa-info-circle me-2"></i>
                    <strong>How to use:</strong> Send this link or QR code to customers. They can fill out the form to register themselves, which helps prevent spam submissions.
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="openFormUrlFromModal()">
                    <i class="fas fa-external-link-alt me-2"></i> Open Form
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Loading Modal -->
<div class="modal fade" id="loadingModal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body text-center">
                <div class="spinner-border text-primary" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
                <p class="mt-2 mb-0">Generating form...</p>
            </div>
        </div>
    </div>
</div>

<!-- Form Details Modal -->
<div class="modal fade" id="formDetailsModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-white">
                <h5 class="modal-title">
                    <i class="fas fa-info-circle me-2"></i>Form Details
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="formDetailsContent">
                <!-- Content will be loaded via JavaScript -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    function generateCustomerForm() {
        // Show loading modal
        const loadingModalElement = document.getElementById('loadingModal');
        const loadingModal = bootstrap.Modal.getOrCreateInstance(loadingModalElement);
        loadingModal.show();
        
        // Generate form via AJAX
        fetch('{{ route("customers.generate-form") }}', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': '{{ csrf_token() }}',
                'Accept': 'application/json'
            },
            body: JSON.stringify({})
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(result => {
            // Hide loading modal
            loadingModal.hide();
            
            if (result.success) {
                // Populate modal with form data
                document.getElementById('formUrl').value = result.form_url;
                document.getElementById('qrCodeImage').src = result.qr_code_url;
                
                // Show the form generation modal
                const formModalElement = document.getElementById('formGenerationModal');
                const formModal = bootstrap.Modal.getOrCreateInstance(formModalElement);
                formModal.show();
                
                // Refresh page after 2 seconds to show new form in list
                setTimeout(() => {
                    window.location.reload();
                }, 2000);
            } else {
                alert('Error: ' + result.message);
            }
        })
        .catch(error => {
            // Hide loading modal
            loadingModal.hide();
            alert('Network error. Please try again. Error: ' + error.message);
            console.error('Error:', error);
        });
    }
    
    function copyFormUrl(url) {
        navigator.clipboard.writeText(url).then(() => {
            // Show success feedback
            alert('Form URL copied to clipboard!');
        }).catch(err => {
            console.error('Failed to copy: ', err);
            alert('Failed to copy to clipboard');
        });
    }
    
    function copyFormUrlFromModal() {
        const formUrlInput = document.getElementById('formUrl');
        formUrlInput.select();
        formUrlInput.setSelectionRange(0, 99999); // For mobile devices
        
        try {
            navigator.clipboard.writeText(formUrlInput.value);
            
            // Show success feedback
            const copyButton = event.target.closest('button');
            const originalHtml = copyButton.innerHTML;
            copyButton.innerHTML = '<i class="fas fa-check"></i> Copied!';
            copyButton.classList.remove('btn-outline-secondary');
            copyButton.classList.add('btn-success');
            
            setTimeout(() => {
                copyButton.innerHTML = originalHtml;
                copyButton.classList.remove('btn-success');
                copyButton.classList.add('btn-outline-secondary');
            }, 2000);
        } catch (err) {
            console.error('Failed to copy: ', err);
            alert('Failed to copy to clipboard');
        }
    }
    
    function openFormUrlFromModal() {
        const formUrl = document.getElementById('formUrl').value;
        window.open(formUrl, '_blank');
    }
    
    function showFormDetails(token) {
        // Fetch form details via AJAX
        fetch(`/api/customer-form/${token}/details`, {
            method: 'GET',
            headers: {
                'Accept': 'application/json',
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Populate modal with form details
                const modalContent = document.getElementById('formDetailsContent');
                modalContent.innerHTML = `
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Form Information</h6>
                            <table class="table table-sm">
                                <tr>
                                    <th>Token:</th>
                                    <td><code>${data.form.token}</code></td>
                                </tr>
                                <tr>
                                    <th>Generated:</th>
                                    <td>${data.form.generated_at}</td>
                                </tr>
                                <tr>
                                    <th>Generated By:</th>
                                    <td>${data.form.generated_by}</td>
                                </tr>
                                <tr>
                                    <th>Expires:</th>
                                    <td>${data.form.expires_at}</td>
                                </tr>
                                <tr>
                                    <th>Status:</th>
                                    <td>
                                        ${data.form.is_expired ? 
                                            '<span class="badge bg-danger">Expired</span>' : 
                                            '<span class="badge bg-success">Active</span>'}
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <h6>Submissions</h6>
                            <div class="text-center py-4">
                                <h1 class="display-1 text-primary">${data.form.submission_count}</h1>
                                <p class="text-muted">Customer(s) Registered</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mt-4">
                        <h6>Form URL</h6>
                        <div class="input-group">
                            <input type="text" class="form-control" value="${data.form.form_url}" readonly>
                            <button class="btn btn-outline-primary" type="button" onclick="copyFormUrl('${data.form.form_url}')">
                                <i class="fas fa-copy"></i> Copy
                            </button>
                        </div>
                    </div>
                    
                    <div class="mt-4">
                        <h6>QR Code</h6>
                        <div class="text-center">
                            <img src="${data.form.qr_code_url}" alt="QR Code" class="img-fluid" style="max-width: 150px;">
                        </div>
                    </div>
                `;
                
                // Show the modal
                const detailsModal = new bootstrap.Modal(document.getElementById('formDetailsModal'));
                detailsModal.show();
            } else {
                alert('Error: ' + data.message);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Failed to load form details');
        });
    }
</script>
@endpush